# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'createplugin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for createplugin
  pod 'PLPlayerKit','2.4.3'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

end
